### ISSUE TITLE
Uncaught ReferenceError: monitoring is not defined

### ISSUE THREAD

**Issue by CalvinWu4** [kylekyle/monitoring#2]
I keep getting this error
I am using a manifest.json to import the .mjs file into a content script

**Comment by kylekyle** [comment]
Can you share a bit of your code? Not sure I understand what you're trying to do.

**Comment by CalvinWu4** [comment]
I want to know how to use this library with a manifest.json file which is used for making browser extensions

**Comment by kylekyle** [comment]
As far as I can tell, extension scripts don't support ES6 modules. I recommend using a bundler, like webpack, parcel, or rollup. Then you can build all of your dependencies - including monitoring - into your bundle and use that in your extension. Hope that helps!
